import React, { useState } from 'react';
import { generateExercisePlan } from '../services/exerciseService';
import { Activity, Dumbbell, Zap } from 'lucide-react';

const Exercise = () => {
    const [plan, setPlan] = useState(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState(null);
    const [selectedGoal, setSelectedGoal] = useState("General fitness");

    const goals = ["Weight loss", "Muscle gain", "General fitness", "Cardio endurance", "Flexibility"];

    const handleGenerate = async () => {
        setIsLoading(true);
        setError(null);
        try {
            const generatedPlan = await generateExercisePlan(selectedGoal);
            setPlan(generatedPlan);
        } catch (err) {
            console.error(err);
            setError("Failed to generate exercise plan. Please try again.");
        } finally {
            setIsLoading(false);
        }
    };

    const formatPlan = (text) => {
        if (!text) return null;
        
        let formatted = text.replace(/\*\*(.*?)\*\*/g, '<strong class="text-calm-teal">$1</strong>');
        formatted = formatted.replace(/\*(.*?)\n/g, '<li class="ml-4 list-disc text-white/80">$1</li>\n');
        formatted = formatted.replace(/## (.*?)\n/g, '<h2 class="text-2xl font-bold text-white mt-8 mb-4 border-b border-glass-border pb-2">$1</h2>\n');
        formatted = formatted.replace(/# (.*?)\n/g, '<h1 class="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-calm-purple to-calm-pink mt-6 mb-4">$1</h1>\n');
        
        // Wrap adjacent li elements into a ul element
        formatted = formatted.replace(/<\/li>\n<li/g, '</li><li');
        formatted = formatted.replace(/(<li.*<\/li>)/g, '<ul class="my-2 space-y-2">$1</ul>');

        return <div className="prose prose-invert max-w-none space-y-4" dangerouslySetInnerHTML={{ __html: formatted }} />;
    };

    return (
        <div className="flex flex-col h-screen bg-slate-900 overflow-y-auto p-6 md:p-8">
            <div className="max-w-4xl w-full mx-auto animate-fade-in-up space-y-8 pb-12">
                
                <div className="text-center glass-card p-8 bg-gradient-to-br from-slate-900 to-slate-800 shadow-2xl border border-glass-border">
                    <div className="w-16 h-16 mx-auto bg-calm-purple/20 rounded-2xl flex items-center justify-center mb-4 border border-calm-purple/30">
                        <Activity className="text-calm-purple w-8 h-8" />
                    </div>
                    <h1 className="text-4xl font-bold text-white mb-4">Personalized Exercise Plan</h1>
                    <p className="text-white/70 max-w-2xl mx-auto text-lg mb-8">
                        Get a highly customized daily workout plan generated by AI based on your age, weight, height, and activity level.
                    </p>

                    <div className="flex flex-wrap justify-center gap-3 mb-8">
                        {goals.map(goal => (
                            <button
                                key={goal}
                                onClick={() => setSelectedGoal(goal)}
                                className={`px-6 py-3 rounded-xl font-medium transition-all ${
                                    selectedGoal === goal 
                                    ? 'bg-calm-purple text-white shadow-[0_0_15px_rgba(168,85,247,0.4)]' 
                                    : 'bg-slate-800 text-white/60 hover:bg-slate-700 hover:text-white border border-glass-border'
                                }`}
                            >
                                {goal}
                            </button>
                        ))}
                    </div>

                    <button 
                        onClick={handleGenerate} 
                        disabled={isLoading}
                        className="px-10 py-4 rounded-xl font-bold text-slate-900 bg-gradient-to-r from-white to-gray-300 hover:from-calm-teal hover:to-calm-blue shadow-glow transform transition-all shadow-xl hover:scale-105 disabled:opacity-50 disabled:hover:scale-100 flex items-center gap-2 mx-auto"
                    >
                        {isLoading ? (
                            <>
                                <div className="w-5 h-5 border-2 border-slate-900 border-t-transparent rounded-full animate-spin"></div>
                                <span>Generating your plan...</span>
                            </>
                        ) : (
                            <>
                                <Zap className="w-5 h-5" />
                                <span>Generate Workout Plan</span>
                            </>
                        )}
                    </button>
                </div>

                {error && (
                    <div className="p-4 bg-calm-pink/10 border border-calm-pink/30 rounded-xl text-calm-pink text-center animate-fade-in-up">
                        {error}
                    </div>
                )}

                {plan && !isLoading && (
                    <div className="glass-card p-8 md:p-10 border border-glass-border animate-fade-in-up bg-slate-800/50 shadow-2xl">
                        <div className="flex items-center gap-4 mb-8 pb-6 border-b border-glass-border">
                            <Dumbbell className="text-calm-teal w-8 h-8" />
                            <div>
                                <h2 className="text-2xl font-bold text-white">Your {selectedGoal} Plan</h2>
                                <p className="text-white/60 text-sm">Generated specifically for your body profile</p>
                            </div>
                        </div>
                        <div className="text-white/90 leading-relaxed text-lg pb-10">
                            {formatPlan(plan)}
                        </div>
                    </div>
                )}
                
            </div>
        </div>
    );
};

export default Exercise;
